all: stat myls mytail recursive-search

stat: stat.c
	gcc -o stat stat.c
myls: myls.c
	gcc -o myls myls.c
mytail: mytail.c
	gcc -o mytail mytail.c
recursive-search: recursive-search.c
	gcc -o recursive-search recursive-search.c
